import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header/Header";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
// Google Font
const inter = Inter({ subsets: ["latin"] });

// Page Metadata
export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      appearance={{ baseTheme: dark }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {/* Global Header */}
            <Header />
            <Toaster
              position="top-center"
              toastOptions={{
                style: {
                  background: "#1f1f1f",
                  color: "#fff",
                  border: "1px solid #333",
                },
              }}
            />
            {/* Main Page Content */}
            <main className="flex-grow">{children}</main>

            {/* Footer */}
            <footer className="border-t border-gray-700 py-8 bg-black text-gray-300 ">
              <div className="container  px-4  m-auto grid grid-cols-1 md:grid-cols-4 gap-8 text-center md:text-left lg:mx-10">
                {/* Branding and Purpose */}
                <div>
                  <h2 className="text-xl font-bold text-white mb-2">
                    AI Career Coach
                  </h2>
                  <p className="text-sm">
                    Your personal AI-powered career assistant. Get tailored
                    guidance, resume feedback, interview prep, and job
                    recommendations all in one place.
                  </p>
                </div>

                {/* Navigation Links */}
                <div>
                  <h3 className="text-lg font-semibold text-white mb-2">
                    Explore
                  </h3>
                  <ul className="space-y-1 text-sm">
                    <li>
                      <a href="/dashboard" className="hover:text-white">
                        Dashboard
                      </a>
                    </li>
                    <li>
                      <a href="/resume-builder" className="hover:text-white">
                        Resume Builder
                      </a>
                    </li>
                    <li>
                      <a href="/interview-prep" className="hover:text-white">
                        Interview Prep
                      </a>
                    </li>
                    <li>
                      <a href="/career-paths" className="hover:text-white">
                        Career Paths
                      </a>
                    </li>
                  </ul>
                </div>

                {/* Resources */}
                <div>
                  <h3 className="text-lg font-semibold text-white mb-2">
                    Resources
                  </h3>
                  <ul className="space-y-1 text-sm">
                    <li>
                      <a href="/blog" className="hover:text-white">
                        Blog
                      </a>
                    </li>
                    <li>
                      <a href="/faqs" className="hover:text-white">
                        FAQs
                      </a>
                    </li>
                    <li>
                      <a href="/community" className="hover:text-white">
                        Community Forum
                      </a>
                    </li>
                    <li>
                      <a href="/support" className="hover:text-white">
                        Support
                      </a>
                    </li>
                  </ul>
                </div>

                {/* Contact and Socials */}
                <div>
                  <h3 className="text-lg font-semibold text-white mb-2">
                    Connect With Us
                  </h3>
                  <div className="flex justify-center md:justify-start space-x-4 text-xl mb-2">
                    <a
                      href="https://linkedin.com"
                      aria-label="LinkedIn"
                      className="hover:text-white"
                    >
                      <i className="fab fa-linkedin"></i>
                    </a>
                    <a
                      href="mailto:support@aicareercoach.com"
                      aria-label="Email"
                      className="hover:text-white"
                    >
                      <i className="fas fa-envelope"></i>
                    </a>
                    <a
                      href="https://twitter.com"
                      aria-label="Twitter"
                      className="hover:text-white"
                    >
                      <i className="fab fa-twitter"></i>
                    </a>
                  </div>
                  <p className="text-sm">Email: support@aicareercoach.com</p>
                </div>
              </div>

              {/* Bottom Bar */}
              <div className="mt-8 border-t border-gray-700 pt-4 text-sm text-gray-400 text-center">
                © {new Date().getFullYear()} AI Career Coach. All rights
                reserved.
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
